spring:
  application:
    name: Trends
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trends
    username: root
    password: Esc141414!

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  jwt:
    secret: ${JWT_SECRET}


springdoc:
  show-login-endpoint: true

cloud:
  aws:
    s3:
      bucket: trends-buckets
    credentials:
      accessKey: ${S3_ACCESSKEY}
      secretKey: ${S3_PASSWORD}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false